# -*- coding: utf-8 -*-
"""scispacy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fi4t0p74Xw4KQ1olDvqQEfdbd16XyAEl
"""

import spacy

# Load the pre-trained medical model
#nlp = spacy.load("en_core_medical")

pip install scispacy

pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.1/en_core_sci_md-0.5.1.tar.gz

pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.5/en_ner_bionlp13cg_md-0.2.5.tar.gz

import spacy
import en_ner_bionlp13cg_md
nlp = en_ner_bionlp13cg_md.load()

!pip show python

nlp = spacy.load("en-core-sci-md")

!python ‐‐version

pip install en_core_sci_md

nlp = spacy.load("en_core_sci_sm")